name: Check with ruff

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install dependencies
        run:  |
          python -m pip install --upgrade pip
          python -m pip install -r ./backend/requirements.txt
          pip install ruff
          pip install autopep8

      - name: lint with ruff, check format with autopep8, run tests
        run: |
          cd backend/
          python -m ruff check .
          python -m autopep8 -r --diff --exit-code ./backend ./api
          python manage.py test

